### ISSUE TITLE
Rendering issue when using a touch screen

### ISSUE THREAD

**Issue by jmgomezpoveda** [jonataswalker/ol-geocoder#101]
Using Firefox 50 in Linux and Chrome in Windows, the search button is not rendered correctly when using a touch screen.

![firefox rendering issue](https://cloud.githubusercontent.com/assets/3722516/20819425/1c51dfa4-b82c-11e6-9b69-a3a9ab066376.png)

**Comment by jmgomezpoveda** [comment]
On further research, it looks as though the issue happens with touch screens, when the .ol-touch event is triggered.

**Comment by jmgomezpoveda** [comment]
So, adding the following styles does fix the size of the component when a touch screen is used and detected:

```
.ol-touch .ol3-geocoder-search {
    height: 39px;
    width: 39px;
}
.ol-touch .ol3-geocoder-search-expanded {
    width: 222px;
}
.ol-touch .ol3-geocoder-input-search {
    top: 5px;
    left: 39px;
}
```

Now, there is a separate issue in both Chrome and Firefox with the default value of the "top" property:

`calc(.5em+65px)`

Both Firefox and Chrome say "Invalid property value".

**Comment by jmgomezpoveda** [comment]
Another style is needed to fix the results popup in touch screens:
```
.ol-touch UL.ol3-geocoder-result {
    left: 39px;
}
```

**Comment by jonataswalker** [comment]
Hey @jmgomezpoveda sorry this long delay but with #109 things will adjust soon.

**Comment by jonataswalker** [comment]
@jmgomezpoveda can you confirm that this is solved with v2.4.0?

**Comment by jmgomezpoveda** [comment]
All my positioning and styling is broken with 2.4.0. I will need to rework the customisation.
In a quick test, the styles still seem to be broken when using a touch screen (though of course my fix no longer works).

**Comment by jonataswalker** [comment]
Sorry for that. v2.4.0 has a big change in CSS selectors.

**Comment by jmgomezpoveda** [comment]
Rendering with 2.4.0 with the traditional control has some glitches, which so far I have been unable to fix in my project.

As per the [jsfiddle](http://jsfiddle.net/jonataswalker/c4qv9afb):

![jsfiddle-2 4 0](https://cloud.githubusercontent.com/assets/3722516/21442893/3ed4845c-c8a1-11e6-8496-c59d7da93848.png)

**Comment by jonataswalker** [comment]
I can't confirm this in my machine, latest version (v3.0.0).

Is this still relevant? @jmgomezpoveda

**Comment by jmgomezpoveda** [comment]
Apologies, I am not working on the website these days, so I won't be able to test it anytime soon.

**Comment by jonataswalker** [comment]
Will reopen if this persist.

**Comment by gHupf** [comment]
This still persists. You can open the fiddle on a touch device to replicate it.

**Comment by jonataswalker** [comment]
Is there anyone willing to provide a fix?

**Comment by jonataswalker** [comment]
Thanks @Nadeflore
