### ISSUE TITLE
Zoom in Shaky

### ISSUE THREAD

**Issue by saviour123** [jonataswalker/ol-geocoder#125]
When you search and try zooming in. The zoom shakes before finally add the place marker. It does not zoom in smoothly. The animation on the README.md looks the same.

**Comment by jonataswalker** [comment]
Hey @saviour123, sorry this long delay.

Are you able to test with the new release (`v3.0.0`)?

**Comment by saviour123** [comment]
Not really. I just been lazy. Would test and submit a pull request if there is more issues.

**Comment by jonataswalker** [comment]
Right. Closing then. Will reopen if you confirm.
