### ISSUE TITLE
Uncaught TypeError using v2.5.0 on Chrome

### ISSUE THREAD

**Issue by andy-br** [jonataswalker/ol-geocoder#126]
When attempting to select a location (after a search), the following error is thrown using Chrome and the latest release:

Uncaught TypeError: r.animate is not a function
    at Object.flyTo (ol3-geocoder.js:7)
    at b.chosen (ol3-geocoder.js:7)
    at HTMLLIElement.<anonymous> (ol3-geocoder.js:7)

**Comment by jonataswalker** [comment]
Hey @andy-br, sorry this long delay.

Are you able to test with the new release (`v3.0.0`)?
