### ISSUE TITLE
Does not any search or there is no response???

### ISSUE THREAD

**Issue by Edgrod** [jonataswalker/ol-geocoder#132]
Sorry, I try to use your Control but isn't work. I don't know what is issue in my code.

<!DOCTYPE html>
<html>
  <head>
    <title>Full Screen map With Geocode Control</title>
    
<link rel="stylesheet" href="https://openlayers.org/en/v4.4.2/css/ol.css" type="text/css">
    
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v4.4.2/build/ol.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.js"></script>
     
     <link href="https://unpkg.com/ol3-geocoder@2.5.0/build/ol3-geocoder.min.css" rel="stylesheet">
     <script src="https://unpkg.com/ol3-geocoder@2.5.0/build/ol3-geocoder.js"></script>
    
    <style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans);
    html,
    body,
    #map {
      width: 100%;
      height: 100%;
      overflow: hidden;
    }
    
    body {
      font: 1em/1.5 "Open Sans", Helvetica, Arial, sans-serif;
      color: #222;
      font-weight: 400;
    }
    
    #map {
      position: absolute;
      z-index: 1;
      top: 0;
      bottom: 0;
    }
    
    .ol-control button {
      background-color: rgba(40, 40, 40, 0.8) !important;
    }
    
    .ol-control button:hover {
      background-color: rgba(40, 40, 40, 1) !important;
    }
    
    .ol-popup {
      position: absolute;
      min-width: 180px;
      background-color: white;
      -webkit-filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.2));
      filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.2));
      padding: 15px;
      border-radius: 10px;
      border: 1px solid #ccc;
      bottom: 12px;
      left: -50px;
    }
    
    .ol-popup:after,
    .ol-popup:before {
      top: 100%;
      border: solid transparent;
      content: " ";
      height: 0;
      width: 0;
      position: absolute;
      pointer-events: none;
    }
    
    .ol-popup:after {
      border-top-color: white;
      border-width: 10px;
      left: 48px;
      margin-left: -10px;
    }
    
    .ol-popup:before {
      border-top-color: #cccccc;
      border-width: 11px;
      left: 48px;
      margin-left: -11px;
    }
    
    .ol-popup-closer {
      text-decoration: none;
      position: absolute;
      top: 2px;
      right: 8px;
    }
    
    .ol-popup-closer:after {
      content: "✖";
    }
    
    </style>
   
 
  </head>
  <body>
  
    <div id="map" tabindex="0"></div>
    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content"></div>
    </div>

    <script>
       var olview = new ol.View({
        center: [0, 0],
        zoom: 2
      }),
      baseLayer = new ol.layer.Tile({
        source: new ol.source.OSM()
      }),
      map = new ol.Map({
        target: document.getElementById('map'),
        view: olview,
        layers: [baseLayer]
      });
    
    //Instantiate with some options and add the Control
    var geocoder = new Geocoder('nominatim', {
      provider: 'google',
      key: '---myKey---',
      lang: 'en',
      placeholder: 'Search for ...',
      limit: 5,
      debug: true,
      autoComplete: true,
      keepOpen: true
    });
    map.addControl(geocoder);
    
    //Listen when an address is chosen
    geocoder.on('addresschosen', function(evt) {
      var feature = evt.feature,
        coord = evt.coordinate;
      content.innerHTML = '<p>' + evt.address.formatted + '</p>';
      overlay.setPosition(coord);
    });
    
    // popup
    var container = document.getElementById('popup'),
      content = document.getElementById('popup-content'),
      closer = document.getElementById('popup-closer'),
      overlay = new ol.Overlay({
        element: container,
        offset: [0, -40]
      });
    closer.onclick = function() {
      overlay.setPosition(undefined);
      closer.blur();
      return false;
    };
    map.addOverlay(overlay);
    
    </script>
  </body>
</html>

**Comment by ehallein** [comment]
I'm having the same problem with google, works fine with OSM. The search spinner just keeps spinning. no debug error is outputted.

**Comment by walkermatt** [comment]
Can you provide a link to demonstrate the issue?

**Comment by ehallein** [comment]
yes here:
http://evev7340.staging-cloud.partnerconsole.net/clients/test/examples/

but I've worked out that it's because changing the google url to https:// appends the URL to calling pages server href. i.e this change broke it:
ar Google = function Google() {

  this.settings = {
    url: '**https**//maps.googleapis.com/maps/api/geocode/json',
    params: {
      address: '',
      key: '',
      language: 'en-US'
    }
  };
};


Is there any other way?

**Comment by walkermatt** [comment]
I think we to update the Google provider so that it's `url` specifies `https` as the protocol and a small change to https://github.com/jonataswalker/ol-geocoder/blob/master/src/js/nominatim.js#L115 so that the protocol is only prepended to the provider url if the protocol isn't already defined.

**Comment by jonataswalker** [comment]
This is fixed in the new released version.
