### ISSUE TITLE
Street number in result?

### ISSUE THREAD

**Issue by tonybierman** [jonataswalker/ol-geocoder#133]
Is there a way to get the searched upon address' street number in the formatted address output?

**Comment by jonataswalker** [comment]
@tonybierman You can always get the original address with:

```javascript
geocoder.on('addresschosen', function (evt) {
	console.log(evt.address.original);
});
```
I guess I will change the output to show the formatted address of provider itself. Already did with OSM #136.

**Comment by tonybierman** [comment]
Thanks for your reply, Jonatas.  

I would like you to know that I appreciate the effort and time you've put into this project. 

Tony

**Comment by tonybierman** [comment]
MapQuest, and thanks again
