### ISSUE TITLE
Mapzen problem

### ISSUE THREAD

**Issue by rbonnefoi** [jonataswalker/ol-geocoder#141]
Dear Jonatawalker,

Thank you so much for the job done.

It works well for me using Nominatim / OSM service, but when I try to use Mapzen / Pelias, I have a message saying I have no connection.

After a short investigation, the problem comes from the fact the api keyword expected by mapzen is 'api_key', while ol-geocoder only use 'key'.

I modified the local code on my server, but you should update the source code to prevent such a problem.

Regards.

Rémi

**Comment by jonataswalker** [comment]
Thanks @rbonnefoi for reporting. Fixed with #142.
