### ISSUE TITLE
Run the geocode by URL's parameters 

### ISSUE THREAD

**Issue by Edgrod** [jonataswalker/ol-geocoder#144]
I have my html with the geocode but I need to run the geocode by  URL's parameters, something like:

http://MyMap.html?address=1526 EvansGardens NW ON&ICON=911&label=STRUCTURE IN FIRE

The parameter ICON and Label I will use in featureStyle.

Thanks you for you help.

**Comment by jonataswalker** [comment]
@Edgrod I have no idea of what your issue is about.

**Comment by Edgrod** [comment]
@jonataswalker Basically, how I can run the ol.geocode by url's parameter?, is possible or not? I know not if this is a issue or request?

**Comment by jonataswalker** [comment]
If you are willing to run this geocoder with a custom provider, [take a look at it](https://github.com/jonataswalker/ol-geocoder/blob/master/examples/custom-provider.js).

**Comment by Edgrod** [comment]
Well, I don't want to use the custom provider, If possible use the geocoder.on by a **default address**?? when is called for first time?

**Comment by jonataswalker** [comment]
Closing as this is too old and I'm not sure if this is still relevant.
