### ISSUE TITLE
Add secure config

### ISSUE THREAD

**Issue by jettcalleja** [jonataswalker/ol-geocoder#151]
What if we add secure config in instantiation:
```javascript
var geocoder = new Geocoder('nominatim', {
  provider: 'mapquest',
  // ...
  secure: true // use https
});
```

so the developer can have a choice if he/she wants to use http or https. What do you think?

**Comment by jonataswalker** [comment]
Well, I think it's time to make HTTPS default. Let's see if anyone really need HTTP.

**Comment by walkermatt** [comment]
I tend to agree that HTTPS should just be the default, if be interested to know if anyone feels they need plain HTTP

**Comment by jonataswalker** [comment]
Can we close this ticket? Almost providers are already `https`.

**Comment by jettcalleja** [comment]
sure
