### ISSUE TITLE
How to use multiple providers at the same time?

### ISSUE THREAD

**Issue by cmangen** [jonataswalker/ol-geocoder#159]
Hello,

first, thank you very much for this excellent extension.

Is it possible to add multiple providers/sources at the same time?

Is it possible to search features in Layers?

Thank you very much.

**Comment by jonataswalker** [comment]
> Is it possible to add multiple providers/sources at the same time?

Not for now. PR welcome.

> Is it possible to search features in Layers?

This is an Openlayers question, it's beyond the scope of this extension.
