### ISSUE TITLE
[Question] Limit to one marker?

### ISSUE THREAD

**Issue by Kardzhilov** [jonataswalker/ol-geocoder#164]
I feel stupid for asking this since it is probably obvious and i am just missing something, but i have been at this for a few days. 
If you go to the [demo for example](https://rawgit.com/jonataswalker/ol-geocoder/master/examples/control-nominatim.html)  and look up two different places, then zoom out you will see both of the markers. 
Old markers do not get removed no matter how many get made. I am not sure if this is intended but i would love it if i could just limit it to one marker, so that when i look up a new address the old marker is no longer there.
Thanks for the great extension :)

**Comment by jonataswalker** [comment]
@Kardzhilov sorry for this long delay, this can be easily achieved with:

```js
var geocoder = new Geocoder('nominatim', {
  // ... some options
});
map.addControl(geocoder);

var geocoderSource = geocoder.getSource();

geocoder.on('addresschosen', function (evt) {
  geocoderSource.clear();
  geocoderSource.addFeature(evt.feature); // add only the last one
});
```
