### ISSUE TITLE
Polygon - LineString Feature

### ISSUE THREAD

**Issue by ozcan-durak** [jonataswalker/ol-geocoder#167]
There could be a feature to and display the whole city instead of point with polygon, or when choosing a road on fulltext search should display the road on map. 

Currently only Lat / Lon is allowed. 
Can be accept point/linestring/polygon or WKT.

I think WKT would be much better.

**Comment by jonataswalker** [comment]
This extension is just a bridge between provider and OpenLayers. You have the original response from the provider and it's up to you what to do with it.
