### ISSUE TITLE
How to use it in an Angular 6 project

### ISSUE THREAD

**Issue by spimou** [jonataswalker/ol-geocoder#173]
I am using OL5 and Angular 6. I am trying to make ol-geocoder work in an Angular 6-based project. So far, angular+ol work fine, but I cannot make the ol-geocoder work.
I have installed ol-geocoder by doing `npm i ol-geocoder --save`

This is my code. In my angular `component.ts` file, I do

```
import Map from 'ol/Map.js';
//import any other ol-related stuff by the same way
import geocoder from 'ol-geocoder';

export class myComponent {
  ngOnInit() {
    this.olmap = new Map({
      controls: defaultControls({
        attributionOptions: {
          collapsible: false
        }
      }).extend([
        new ZoomToExtent({
          extent: [
            813079.7791264898, 5929220.284081122,
            848966.9639063801, 5936863.986909639
          ]
        }),
        new FullScreen({})
      ]), 
      layers: [this.tilelayer,this.vectorlayer],
      target: 'map',      
      view: this.view,
      projection: 'EPSG:3857'
    });

    const geoco = new geocoder('nominatim', {
      provider: 'osm',
      lang: 'gr',
      placeholder: 'Search for ...',
      limit: 5,
      debug: false,
      autoComplete: true,
      keepOpen: true
    });
    this.olmap.addControl(geoco);
  }//ngOnInit
}//myComponent 
```

I get no errors in any console, but I cannot see the ol-geocoder in the UI. I even removed the `ZoomToExtent` control, in case the ol-geocoder was under it, but still no luck. 

How to make it work? 

Thank you

**Comment by JulidaRocks** [comment]
@spimou any success so far? Does not work in my Angular 6 project, too.

**Comment by jonataswalker** [comment]
Sorry the delay but I'm not finding enough time to work on a solution.

Any help? @walkermatt ?

**Comment by walkermatt** [comment]
Have you included the ol-geocoder CSS in your project?

**Comment by spimou** [comment]
Hi there again. Sorry for super late answer. I could not find a solution and left my issue frozen But I just found a solution, out of luck, by doing something else. In my ol map's view I had 

```
    this.view = new View({  
      /*zoom: 9*/ // I had this, and I fixed it and set it as the following:
      maxZoom:11
    });
```
So now geocoder kind of works. It shows on the map, but the CSS is messed up. And I can see none of my layers or any of my points in my vector layer. I tried to set the geocoder CSS file in the `angular.json` like `"styles": ["../node_modules/ol/ol.css", "src/styles.css","../node_modules/ol-geocoder/dist/ol-geocoder.css"],` , but nothing. No CSS, no layers

The structure of my angular component is

```
import * as geocoder from 'ol-geocoder'; 

  ngOnInit() {    
    this.view = new View({      
      center: [2641556.686163,4578203.452144],  
      maxZoom:11
    });

    this.olmap = new Map({
      controls: defaultControls({
        attributionOptions: {
          collapsible: false
        }
      }).extend([
        new ZoomToExtent({
          extent: [2282941.0756187593,4616840.069333635,2493907.273685846,4769714.125903988]
        }),
        new FullScreen({}),
        new layerswitch({}),
        new geocoder('nominatim', {
          provider: 'osm',
          lang: 'gr',
          placeholder: 'search',
          limit: 5,
          debug: false,
          autoComplete: true,
          keepOpen: false
        })
      ]), 
      layers: [this.tilelayer, this.binglayer, this.vectorlayer, this.geoloclayer, this.coordlayer,this.relatedlayer],
      target: 'map',      
      view: this.view,
      projection: 'EPSG:3857'
    });
 
    this.selectClick = new Select({
      condition: click,
      layers:[this.vectorlayer],
      style:styleFunctionClicked      
    });
```

How can I make this work? Thank you

**Comment by shastaxc** [comment]
If you do `import` * as geocoder from 'ol-geocoder';` it should work. Personally, I imported as Geocoder (capital G) to better match the docs.

**Comment by jonataswalker** [comment]
Closing as I don't think this is still relevant.
