### ISSUE TITLE
Set marker style and display

### ISSUE THREAD

**Issue by mebels** [jonataswalker/ol-geocoder#174]
Hi,
nice feature. Thanks for that.

How it is realized to change the marker or remove the marker?

I found this and make a litte core hack:

```/*C.featureStyle=[new a({image:new i({scale:.7,src:g})})]*/C.featureStyle=[new a({zIndex:-100})]```

Can you make the marker style at a option?

**Comment by jonataswalker** [comment]
See [constructor](https://github.com/jonataswalker/ol-geocoder#constructor) options - `featureStyle`. Isn't it what you're looking for?

**Comment by mebels** [comment]
I have found the `featureStyle` in the code, but without an example don't understand it. It's for `geocoder.on`?

**Comment by jonataswalker** [comment]
Not mentioning the code. It's on README.

Here's a demo: http://jsfiddle.net/jonataswalker/cs8Lx3zd/

**Comment by mebels** [comment]
Thanks. Sorry i mean the `var geocoder = new Geocoder('nominatim', {`.
OK, i must put a complete ol.style.Style in it.
I had only put `zIndex: -100` and ```featureStyle: { zIndex: -100 }```

```
featureStyle: new ol.style.Style({
zIndex: -100
})
```
