### ISSUE TITLE
ol-geocoder with own view.animate?

### ISSUE THREAD

**Issue by mebels** [jonataswalker/ol-geocoder#175]
Hi, your write:
```
geocoder.on('addresschosen', function(evt) {
  geocoder.preventDefault();
  // add your own fly function
});
```
But that's easy to say, but not easy to make. The <li> elements with the click function are creating by writing in the search input box and the <li> elements have no id oder classname. That makes it hard to wirte a "own fly function".
`view.animation` needed some values.
https://openlayers.org/en/latest/examples/animation.html

For what is the `<a href="#">...</a>` in the `<li>`? Only for `cursor:pointer`?

I have make a little core hack for a better fly animation:
Original:
```e.getView().animate({duration:s,resolution:n},{duration:s,center:t,zoom:10})```
core hack:
```e.getView().animate({duration:s,center:t,zoom:14},{duration:s,resolution:n,zoom:14})```

The fly animation is a central function in your module. Please make the animation values as a option.

**Comment by walkermatt** [comment]
There is an example of defining a custom `addresschosen` event handler in the [custom-provider.js example](https://github.com/jonataswalker/ol-geocoder/blob/master/examples/custom-provider.js#L40-L46).
