### ISSUE TITLE
IE11 throws error message 'No internet connection'

### ISSUE THREAD

**Issue by uweDuesing** [jonataswalker/ol-geocoder#177]
Hi,

When using any browsers but IE11 the geocoder works fine.

But when using it in connection with Angular 6 + IE11 it unfortunately shows and error message underneath the input field 'Error! No internet connection'
![image](https://user-images.githubusercontent.com/100846/45858426-6ec40000-bdb1-11e8-94eb-c38d88e65f6e.png)

**Comment by wintermoor** [comment]
Same here, but with FIrefox 61 having this error, too.

**Comment by walkermatt** [comment]
I've successfully used ol-geocoder on IE11 by including polyfills for features missing in IE11. This is the polyfills.io script I'm using (covers OpenLayers, ol-geocoder and JSTS so you might not need everything):

````html
    <!-- Polyfills required for older browsers such as Internet Explorer -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL,Object.assign,Array.prototype.find,Array.prototype.fill,Array.prototype.includes,Number.isInteger,Number.isNaN,Number.isFinite,Math.trunc"></script>
````
