### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Cherviakov** [jonataswalker/ol-geocoder#178]
Version 69.0.3497.100 (Official Build) (64-bit) for linux

https://rawgit.com/jonataswalker/ol-geocoder/master/examples/control-nominatim.html
https://rawgit.com/jonataswalker/ol-geocoder/master/examples/custom-provider.html

Refused to execute script from 'https://rawgit.com/jonataswalker/ol-geocoder/master/dist/ol-geocoder.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.

**Comment by jonataswalker** [comment]
Thanks for reporting @Cherviakov but this [fiddle](http://jsfiddle.net/jonataswalker/c4qv9afb/) is still working!

I'll change the links.

**Comment by gabriel9130** [comment]
The demo was still npt working, I discovered thats because the dist folder was deleted in a commit and it is essential for the demo. Maybe you should put back this folder for the persons who want to use your project? Thanks!

**Comment by papermachine** [comment]
I noticed that the .gitignore of this repo is masking the `dist` directory. Is there a good reason for this? My pull request #185 has the `dist` directory added again so the examples will work.
