### ISSUE TITLE
Getting wrong destination when projection is EPSG:4326

### ISSUE THREAD

**Issue by kayaon** [jonataswalker/ol-geocoder#179]
Hello sir,
This geocoder is great but i have some trouble when i set projection: 'EPSG:4326' as ol.View option.
Here is the code and some image outputs.
If you give me some suggestions, i will be really grateful.

```javascript
var olview = new ol.View({ center: [0, 0], zoom: 2,
            units: 'degree',
            minZoom:4,
            projection: 'EPSG:4326'
          }),
    baseLayer = new ol.layer.Tile({ source: new ol.source.OSM() }),
    map = new ol.Map({
      target: document.getElementById('map'),
      view: olview,
      layers: [baseLayer]
    });
    
// popup
var popup = new ol.Overlay({
    element: document.getElementById('popup')
  });
  map.addOverlay(popup);

//Instantiate with some options and add the Control
var geocoder = new Geocoder('nominatim', {
  provider: 'osm',
  lang: 'en',
  placeholder: 'Ara ...',
  limit: 5,
  debug: false,
  autoComplete: true,
  keepOpen: true, 
});
map.addControl(geocoder);
```

and here is the result:
![screenshot_2](https://user-images.githubusercontent.com/39480788/47007669-6907d300-d141-11e8-9314-94997cc8c539.png)

At HTML part i just used div map and some source scripts.
Thanks.

**Comment by umbe1987** [comment]
@jonataswalker could it be related to not transforming the coordinates in [flyTo()](https://github.com/jonataswalker/ol-geocoder/blob/a2b43ea105a120a1ef47c487917c8a7b50c011e5/src/helpers/mix.js#L49) function of helpers/mix.js?
Just an idea...
Maybe doing something like this might work:

```
export function flyTo(map, coord, duration, resolution) {
  resolution = resolution || 2.388657133911758;
  duration = duration || 500;
  projection = map.getView().getProjection();
  map.getView().animate(
    { duration, resolution },
    { duration, center: proj.transform(coord, 'EPSG:4326', projection) }
  );
}
```

**Comment by xitox97** [comment]
Anyone know how to fix this? I also have this problem. need to change to projection: 'EPSG:4326'

**Comment by jonataswalker** [comment]
Sorry but is this still relevant?
