### ISSUE TITLE
Geocoder not working

### ISSUE THREAD

**Issue by pedrofwanderley** [jonataswalker/ol-geocoder#180]
Hi, i'm trying to use geocoding service on my project with openlayers 3, i've tried everything but i keep getting the same error on console "Uncaught ReferenceError: Geocoder is not defined", i'm leaving the source code snippet below:

 function search() {
	var geocoder = new Geocoder('nominatim', {
  provider: 'osm',
  lang: 'en',
  placeholder: Digite o endereço',
  // targetType: 'text-input'
  autoComplete: true,
  limit: 8
});

map.addControl(geocoder);
  
};

obs: i've downloaded your project, and tried to run it(the examples) - just to be sure that the problem wasn't on my code- and the same error occurred!

**Comment by pedrofwanderley** [comment]
obs: i've downloaded your project, and tried to run it(the examples) - just to be sure that the problem wasn't on my code- and the same error occurred!

**Comment by gabriel9130** [comment]
You need the dist folder to make it works, but it was deleted in the recent commits, I don't know why. When I come back to the last version, it works well! Geocoder is not defined because it is a file (as well as the .css) hat were in the dist folder.

**Comment by pedrofwanderley** [comment]
> You need the dist folder to make it works, but it was deleted in the recent commits, I don't know why. When I come back to the last version, it works well! Geocoder is not defined because it is a file (as well as the .css) hat were in the dist folder.

That was the problem, thanks a lot!
