### ISSUE TITLE
Adding geocoder option: initial search

### ISSUE THREAD

**Issue by gabriel9130** [jonataswalker/ol-geocoder#181]
Hey :) ,
I would like to be able to add the option InitialSearch in the object Geocoder, so that the first view source is the one searched by geocoder. So like this:

var geocoder = new Geocoder('nominatim', {
    provider: 'photon',
    targetType: 'glass-button',
    lang: 'en',
    placeholder: 'Search for ...',
    limit: 1,
    keepOpen: false,
    initSearch: 'Sherbrooke'
  });

So the first view is in Sherbrooke. I looked at the code, is it to add in Nominatim a function call to intialize that city? I guess this funtion call will be very similar to the function named Naminatim.query, but I will need to modify it?

Thank you!

**Comment by gabriel9130** [comment]
I made it work.  The code is not the cleanest one, but if some one needs that you can ask me and I will send you my modificiations.

**Comment by jonataswalker** [comment]
I pretty sure this can be done in userland.
