### ISSUE TITLE
rawgit shutdown

### ISSUE THREAD

**Issue by pathmapper** [jonataswalker/ol-geocoder#184]
https://rawgit.com/

> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019.

It is currently used here:

https://github.com/jonataswalker/ol-geocoder/blob/76877d508575ba7d229a8f16d4300da9165109de/konstants/index.js#L21

https://github.com/jonataswalker/ol-geocoder/blob/76877d508575ba7d229a8f16d4300da9165109de/README.md#L28

**Comment by jonataswalker** [comment]
I guess this is fixed by #220
