### ISSUE TITLE
Clearing marker from search result when entering a new search

### ISSUE THREAD

**Issue by TobiCook** [jonataswalker/ol-geocoder#200]
Hello @jonataswalker, thank you for providing the ol-geocoder.

We used the code to get an address search function for our map in our project. 

Now we want to add the function, that if there is a new search entered, the old markers should automatically be cleared from the OSM map and the new search result should show up. At the moment, all the markers are staying on the map.

Is there a solution to clear the markers from the search results?
Regards

**Comment by jonataswalker** [comment]
Hi @TobiCook 

Something like this?

```javascript
geocoder.on('addresschosen', function (evt) {
  console.info(evt);
  geocoder.getSource().clear();
  geocoder.getSource().addFeature(evt.feature);
});
```

http://jsfiddle.net/jonataswalker/bq30mnwt/
