### ISSUE TITLE
Geocoder map marker loses precision when zooming out

### ISSUE THREAD

**Issue by smillerk2** [jonataswalker/ol-geocoder#201]
Great library. However, there is a bug when zooming out. Using your [Fiddle ](http://jsfiddle.net/jonataswalker/c4qv9afb/)"as is", when you enter a location (e.g. Toronto) click the zoom out button a few times. You will see the marker re position itself with every zoom change until eventually it becomes inaccurate. 

How can the Geocoder marker position be retained so that it's accurate when the user zooms in and out?

**Comment by gHupf** [comment]
This should be a problem of how the marker is made. If you look at the [marker.png](https://raw.githubusercontent.com/jonataswalker/map-utils/master/images/marker.png) the middle of the picture is not the tip of the marker. So if you are zoomed in really far, it seems like the marker is in correct position (even though it isn't). If you zoom out the middle of the picture stays at the correct position, but not the tip of the marker.

An easy workaround is to display your own marker. You can adjust the ol-geocoder.js and add your own marker.

**Comment by jonataswalker** [comment]
@gHupf would you provide a PR to fix this behavior?

**Comment by jonataswalker** [comment]
Not sure if this is still relevant, it looks like a solution can be provided on userland.
