### ISSUE TITLE
"Click" event propogating to map when choosing a result

### ISSUE THREAD

**Issue by walkermatt** [jonataswalker/ol-geocoder#202]
I've just been updating an application to OpenLayers v6.1.1 and I experienced an issue with events propagating to the map when I click to choose a result. I noticed the issue as I have a handler listening to the map's `singleclick` event which centres the map.

I think it's related to [OpenLayers #6948](https://github.com/openlayers/openlayers/issues/6948#issuecomment-389236565).

I've worked around it by updating `Nominatim.prototype.createList` to also listen to and stop propagation for `pointerdown` on `li`.

```js
      li.addEventListener(
        'pointerdown',
        function (evt) {
          evt.stopPropagation();
        },
        false
      );
```

@jonataswalker have you seen this/ any thoughts on whether we should add this workaround to ol-geocoder?

**Comment by walkermatt** [comment]
I've looked into this a little more and I think the issue is due to the result list being removed from the DOM in the event handler resulting in [`PluggableMap` not being able to determine if the event originated from a child of `overlayContainerStopEvent_` as `target.parentElement` is `null`](https://github.com/openlayers/openlayers/blob/master/src/ol/PluggableMap.js#L938)

**Comment by jonataswalker** [comment]
@walkermatt I'm not able right now to take a look into this. Counting on you to handle it.

**Comment by walkermatt** [comment]
I've updated [openlayers/openlayers #6948](https://github.com/openlayers/openlayers/issues/6948#issuecomment-565375694) with my current thoughts; I'm hoping we might be able to fix in OpenLayers itself.

**Comment by jonataswalker** [comment]
@walkermatt will this issue be solved by https://github.com/openlayers/openlayers/pull/10502?

**Comment by walkermatt** [comment]
Yes it should be 👍

**Comment by jonataswalker** [comment]
Closing as the PR mentioned is merged. Okay?
