### ISSUE TITLE
Is there a way to make two ajax calls in each search?

### ISSUE THREAD

**Issue by rapto** [jonataswalker/ol-geocoder#203]
In our application, we have to perform two queries against two different services to obtain the results. Is there a way to achieve that with a custom provider? Thank you.

**Comment by walkermatt** [comment]
Currently the http requests are made internally, a custom provider specifies the URL and query string parameters via `getParameters` which ol-geocoder then fetches.

I don't think there is an easy way to call more than one source via a custom provider. I think that leaves you with:

* Roll your own search control using a generic auto complete component
* Implement a single end-point server-side that combines the two end-points that you can call via a custom provider.

**Comment by rapto** [comment]
I think I will implement a server side proxy to make both calls. I still don't have enough expertise in JS to expose the request in order to override it. I made a NominatimLike class, derive the current Nominatim class, create my two-call-query method on the new class and expose the class in the factory. But I fail in the bureaucracy of the packaging.
