### ISSUE TITLE
Custom provider (url string)

### ISSUE THREAD

**Issue by Bali05** [jonataswalker/ol-geocoder#204]
I'm trying to use a custom provider, but the url string has to contain "?query=" instead of "?q=".
How can I change this?

**Comment by walkermatt** [comment]
That should be fine. In `getParameters` you return an object with a `params` property which is itself an object with the query string parameter name: value pairs that need to be sent in the request.

This example would result in two query string parameters: `&query={search string}&key=my-api-key`

```js
      getParameters: function(opt) {
        return {
          url: url,
          callbackName: 'callback',
          params: {
            query: opt.query,
            key: 'my-api-key'
          },
        };
      },
```

**Comment by Bali05** [comment]
Thank you.

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Jan. 23, 2020 at 10:28 schrieb Matt Walker<notifications@github.com>:   
That should be fine. In getParameters you return an object with a params property which is itself an object with the query string parameter name: value pairs that need to be sent in the request.

This example would result in two query string parameters: &query={search string}&key=my-api-key
      getParameters: function(opt) {
        return {
          url: url,
          callbackName: 'callback',
          params: {
            query: opt.query,
            key: 'my-api-key'
          },
        };
      },
