### ISSUE TITLE
Setting address, city, etc by code

### ISSUE THREAD

**Issue by gusarg81** [jonataswalker/ol-geocoder#205]
Hi,

I was using before API from google maps, using gmaps.js to get map position by settings address, city, postal code, etc to its geocoder, all by code (not using a search input). It is possible to do it like this with ol-geocoder? I don't find it in the docs. 

Thanks.

**Comment by nobohan** [comment]
+1 I have the same requirement, actually.

**Comment by jonataswalker** [comment]
Are you able to investigate if the desired provider have this feature?

**Comment by gusarg81** [comment]
Hi,

I replaced with python geocoder lib (since I've develop with Django) and works perfect.
