### ISSUE TITLE
"Error! No Internet Connection?" message.

### ISSUE THREAD

**Issue by lewinmadrid** [jonataswalker/ol-geocoder#208]
This error message appears when using Nominatim. Occurs in the example in  jsFiddle
To fix, remove the slash at the end of the url.

Before;
    https://nominatim.openstreetmap.org/search/
After:
    https://nominatim.openstreetmap.org/search

**Comment by jonataswalker** [comment]
Cannot reproduce! Are you able to provide a demo?

**Comment by jonataswalker** [comment]
Closing but feel free to reopen with some reproduction.
