### ISSUE TITLE
Geocoder without arrow ?

### ISSUE THREAD

**Issue by sylvain258** [jonataswalker/ol-geocoder#210]
Hi,

It's possible to drop the arrow on each view ? (arrow yellow and grey)
![Capture](https://user-images.githubusercontent.com/33748168/82963834-21efee00-9fc4-11ea-99f4-fa0c01d73544.PNG)

Thanks

**Comment by MGotink** [comment]
You could pass an empty style during instantiation:
```js
var geocoder = new Geocoder('nominatim', {
    provider: 'osm',
    targetType: 'text-input',
    featureStyle: new ol.style.Style()
});
```
