### ISSUE TITLE
Map Marker with a initial location?

### ISSUE THREAD

**Issue by ravindragullapalli** [jonataswalker/ol-geocoder#212]
Is it possible to show map marker initially by providing longitude and latitude soon after loading the map?

**Comment by jonataswalker** [comment]
How it this related to this plugin? Isn't it possible on userland?

**Comment by ravindragullapalli** [comment]
I could not understand what userland is.

However, I could manage to handle it with this code snippet.

```
var coordinates = olProj.fromLonLat([longitude, latitude]);
this.geocoder.dispatchEvent({
      type: 'addresschosen',
      coordinate: coordinates
})

```

May be someone will be benefitted.

Closing this issue.
