### ISSUE TITLE
JS issue in Angular8 Project

### ISSUE THREAD

**Issue by louischamaillard** [jonataswalker/ol-geocoder#244]
Hi ! I dont really know if I can ask for this here but here's the problem, I got this error in my console : 

![image](https://user-images.githubusercontent.com/52458580/162235869-d4fb7f28-ea5b-4a05-b31c-50129d45db86.png)

I've tried with both js scripts you gave in the README file, and got the same error each time.

For the css, I think there is no problem but as long as I can't load the JS, I just can't see any html element.

I'll be checking there once a day with hope that you could help me.
Thanks !

**Comment by louischamaillard** [comment]
got the solution, no problem

**Comment by AdityaaBangari** [comment]
Hi, can you please tell me what was the solution. 

I'm facing the same issue, it would be of great help if you can provide the solution for this

**Comment by louischamaillard** [comment]
I think (not sure, been a long time), that I was loading JS directly into my base.html. I actually created the 2 js scripts into my assets folder, then copy past the code you gave.

Hope it'll help, have a great day !
