### ISSUE TITLE
URL for OSM provider is wrong

### ISSUE THREAD

**Issue by lonvia** [jonataswalker/ol-geocoder#267]
You have a wrong URL to nominatim.openstreetmap.org here https://github.com/jonataswalker/ol-geocoder/blob/c8d7212a917664fc8771852d0d943612f7c1c1d4/src/providers/osm.js#L10

The URL must not have a final slash. Please note that an URL with a slash is likely to break very soon.

**Comment by jonataswalker** [comment]
Fixed #268, published `4.2.0`
