### ISSUE TITLE
Attach control to existing HTML element / target

### ISSUE THREAD

**Issue by sclose** [jonataswalker/ol-geocoder#60]
Is there a simple way to attach this control to an existing html element?  When defining stock ol3 controls, for instance, one can[ specify a target ](http://openlayers.org/en/master/apidoc/ol.control.Control.html) to which that control may attach outside of the viewport, and this functionality would be an excellent addition to your already useful ol3 extension.

**Comment by jonataswalker** [comment]
Yeah @sclose, this is definitely has to be done. I'll come up with something.

**Comment by allenhwkim** [comment]
Just to be helpful to others,  I have completed this feature from a separate repository of my own. https://github.com/allenhwkim/geocoder

An example can be found here.
https://rawgit.com/allenhwkim/geocoder/master/app/index.html

The full example with React/OpenLayers Control with this also can be found here.
https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/custom/geo-code
